apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: es-log
  namespace: elastic-system
spec:
  version: "7.3.0"
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: es-log-es-http.elastic-system.svc.cluster.local
        - dns: es-log-es-http.elastic-system.svc
        - dns: es-log-es-http
  nodes:
  - name: quickstart
    config:
      node.attr.attr_name: attr_value
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 8Gi
              cpu: 4
            limits:
              memory: 10Gi
              cpu: 8
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms6g -Xmx6g"
    nodeCount: 5
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: yc-network-ssd
        resources:
          requests:
            storage: 300Gi
