apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: "7.3.0"
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: elasticsearch-sample-es-http.elastic-system.svc.cluster.local
        - dns: elasticsearch-sample-es-http.elastic-system.svc
        - dns: elasticsearch-sample-es-http
  nodes:
  - name: quickstart
    config:
      node.attr.attr_name: attr_value
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8Gi
              cpu: 4
            request:
              memory: 10Gi
              cpu: 8
    nodeCount: 5
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 300Gi
